/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TestimonialIndexImport } from './routes/testimonial/index'
import { Route as ProdukIndexImport } from './routes/produk/index'
import { Route as KontakIndexImport } from './routes/kontak/index'
import { Route as FaqIndexImport } from './routes/faq/index'
import { Route as AboutIndexImport } from './routes/about/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestimonialIndexRoute = TestimonialIndexImport.update({
  path: '/testimonial/',
  getParentRoute: () => rootRoute,
} as any)

const ProdukIndexRoute = ProdukIndexImport.update({
  path: '/produk/',
  getParentRoute: () => rootRoute,
} as any)

const KontakIndexRoute = KontakIndexImport.update({
  path: '/kontak/',
  getParentRoute: () => rootRoute,
} as any)

const FaqIndexRoute = FaqIndexImport.update({
  path: '/faq/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqIndexImport
      parentRoute: typeof rootRoute
    }
    '/kontak/': {
      id: '/kontak/'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakIndexImport
      parentRoute: typeof rootRoute
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukIndexImport
      parentRoute: typeof rootRoute
    }
    '/testimonial/': {
      id: '/testimonial/'
      path: '/testimonial'
      fullPath: '/testimonial'
      preLoaderRoute: typeof TestimonialIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutIndexRoute,
  FaqIndexRoute,
  KontakIndexRoute,
  ProdukIndexRoute,
  TestimonialIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about/",
        "/faq/",
        "/kontak/",
        "/produk/",
        "/testimonial/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/faq/": {
      "filePath": "faq/index.tsx"
    },
    "/kontak/": {
      "filePath": "kontak/index.tsx"
    },
    "/produk/": {
      "filePath": "produk/index.tsx"
    },
    "/testimonial/": {
      "filePath": "testimonial/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
